version: '3'
services:
  nginx:
    image: nginx:1.21
    container_name: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./key/certificate.crt:/etc/ssl/certificate.crt # SSL 인증서 파일 마운트
      - ./key/private.key:/etc/ssl/private.key # SSL 키 파일 마운트
    depends_on:
      - nodejs

  nodejs:
    build:
      context: ../
      dockerfile: ./deployment/nodejs/Dockerfile

    container_name: nodejs
    restart: always
    ports:
      - '8000:8000' # 호스트 포트 8000으로 매핑
    environment:
      - PORT=8000
    volumes:
      - ../:/usr/src/app
      - /usr/src/app/node_modules
